### ISSUE TITLE
[Docs] 插件模板使用文档

### ISSUE THREAD

**Issue by arvinxx** [lobehub/chat-plugin-template#1]

**Comment by arvinxx** [comment]
https://github.com/lobehub/chat-plugin-template/commit/d5be83db2c624ffa1dac7c53403fd032805cfd93

https://github.com/lobehub/chat-plugin-sdk/commit/ac1ec3c14e47f716c01104fe2078e56319247e38

**Comment by tonyyls** [comment]
<img width="835" alt="image" src="https://github.com/lobehub/chat-plugin-template/assets/1624736/07a43542-cd8e-46ca-969d-1c9fa28a2cc9">

bun install 正常安装， 接下来 bun dev 就报如上错误了。烦请看看。
