### ISSUE TITLE
bun dev启动报错

### ISSUE THREAD

**Issue by tonyyls** [lobehub/chat-plugin-template#18]
### 🧐 问题描述 | Proposed Solution

bun install 正常安装， 接下来 bun dev 就报如上错误了。烦请看看
<img width="848" alt="image" src="https://github.com/lobehub/chat-plugin-template/assets/1624736/48a04573-c736-4996-929c-e4b53b6c9bce">

**Comment by arvinxx** [comment]
@tonyyls pull下，然后重新bun dev试试，前一个 commit 写错了依赖版本号

**Comment by tonyyls** [comment]
@arvinxx   pull 后， 删掉node_modules，重新 bun install, 再 bun dev ，报错依旧。
<img width="715" alt="image" src="https://github.com/lobehub/chat-plugin-template/assets/1624736/3546f586-c9c8-49d5-bba1-ceed3fe108de">

环境信息：
<img width="465" alt="image" src="https://github.com/lobehub/chat-plugin-template/assets/1624736/449b6727-2df3-426f-9e55-1dc923cca30d">


麻烦再看看。

**Comment by arvinxx** [comment]
可能是你 node 环境版本太低了，试试升级下 node？最新 LTS 都到 node 20 了。我本地跑是ok的。 node v18

**Comment by tonyyls** [comment]
@arvinxx Done， 升级到 16 即可。Thanks .

![image](https://github.com/lobehub/chat-plugin-template/assets/1624736/9978540f-562d-49e8-bdb5-78dcd8c16036)
