### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by heqiangjiangxi** [lobehub/chat-plugin-template#21]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

npm run build失败
![image](https://github.com/lobehub/chat-plugin-template/assets/95673170/b13a7e93-53f7-4bde-a28c-c893fce90a16)

**Comment by mushan0x0** [comment]
@arvinxx 同样的构建失败
https://github.com/mushan0x0/lobe-pollinations-ai/actions/runs/7364158835/job/20044296641
https://github.com/lobehub/chat-plugin-template/actions/runs/7354468680/job/20021714050

**Comment by arvinxx** [comment]
@mushan0x0 fixed https://github.com/lobehub/chat-plugin-template/commit/6c55a6090f4145ad4faa0941a64d297e36d23b99

gateway 移除 runtime 配置即可。后续会优化 Gateway 的使用，不让 gateway 影响项目的正常构建
