### ISSUE TITLE
[Bug] gateway.ts 去掉 runtime 后报跨域错误

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/chat-plugin-template#22]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

[gateway.ts](https://github.com/mushan0x0/lobe-pollinations-ai/blob/main/src/pages/api/gateway.ts) 已经去掉了，构建成功了，但是使用时报跨域错误

<img width="1258" alt="image" src="https://github.com/lobehub/chat-plugin-template/assets/29084441/cee972c9-4aa8-467c-9ce2-4bed42724f06">

**Comment by arvinxx** [comment]
线上版本不应该增加 `gateway` 字段，只有 dev 下才需要添加 gateway

**Comment by mushan0x0** [comment]
ok 了
