### ISSUE TITLE
lobe在请求插件服务时的请求体是什么样的？

### ISSUE THREAD

**Issue by lucasfen** [lobehub/chat-plugin-template#38]

**Comment by lucasfen** [comment]
我们在自定义插件测试时，插件服务收到的请求体是：`{
  "identifier": "coremon",
  "arguments": "{"param1":"value1", "param2":"value2"}",
  "apiName": "Coremon",
  "type": "default"
}`。 我们在完成插件的安装后，插件服务收到的请求体是:`{"param1":"value1","param2":"value2"}`

**Comment by arvinxx** [comment]
"identifier": "coremon", "arguments": "{"param1":"value1", "param2":"value2"}", "apiName": "Coremon", "type": "default" }

这个是 lobechat 插件网关收到的参数，然后网关应该基于 coremon 以及 apiName 查到这个插件是哪个，然后再把 arguments 参数发到这个插件服务去
